### PR TITLE
Fix Cuda compilation and format README

### PR DESCRIPTION
**Pull request by hadim**
ping @klyshko 

I am trying to compile your code and I found the following Cuda flags to make it compile the code on my system (Ubuntu 18.10 and Cuda 10.1).

Linking still fails but I am working on it.

I have also reformated your README.

Hope it helps.

Best.

### CODE REVIEW

**Comment by klyshko** [comment]
Hey @hadim! 

Thank you for the interest towards my code and suggested modifications.

What is your specific interest and the goal? Although I stopped working on this project a while ago, I have several modifications of the code for mimicking different experiments:

- assembly/disassembly of the MT 
- pulling of the bead in optical trap (the on the gif animation)
- wrapping of the sheet-like MT fragment
- MT growth on the adhesive surface

I can help you out to set up the system that you need.

Best,
@klyshko

**Comment by hadim** [comment]
I found your repo totally by chance and so at the moment I don't have any specific project in mind but I am very curious what your model can do and how easily it can be integrated into a Python workflow (C++ is easy to interface with Python).

Have you published a paper about this model? Do you have documentation?

FYI: The code compiles and runs on an Ubuntu 18.10 + Nvidia 418 + Cuda 10.1.

Thanks for being helpful.

**Comment by klyshko** [comment]
Hey,

I haven't published the paper wih the model yet, but at the moment another person is working on the project (getting new verifications for the model parameters). Once we publish all this I will create a documentation page. I hope it will get there soon - manuscript is in preparation. 

Thank you a lot

**Comment by hadim** [comment]
Exciting. Let me know!

**Pull request merged**
